# NumPy

**Задание 1.**
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и 
единицами.

In [9]:
import numpy as np

In [63]:
rows, cols = np.indices((8, 8))

print(f'rows\n{rows}\n')
print(f'cols\n{cols}\n')

matrix = rows + cols
print(f'matrix\n{matrix}\n')


chess_matrix = matrix % 2
print(f'chess_matrix\n{chess_matrix}')

rows
[[0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7]]

cols
[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]

matrix
[[ 0  1  2  3  4  5  6  7]
 [ 1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  9]
 [ 3  4  5  6  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]
 [ 7  8  9 10 11 12 13 14]]

chess_matrix
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]

**Задание 2.**
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания 
необходимо использовать функцию arange.

In [75]:
matrix = np.zeros((5, 5), dtype=int)
row = np.arange(5)
new_matrix = matrix + row
print(new_matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]

**Задание 3.**
Создать массив 3x3x3 со случайными значениями.

In [81]:
rand_array = np.random.random((3, 3, 3))
print(rand_array)

[[[0.72239041 0.04364346 0.91083196]
  [0.93690576 0.93275399 0.85405958]
  [0.01141346 0.46064548 0.91386006]]

 [[0.4722756  0.23766332 0.11281101]
  [0.84377725 0.33660973 0.53198038]
  [0.37228052 0.17217182 0.1264307 ]]

 [[0.49664409 0.09766719 0.98282637]
  [0.04755458 0.26375639 0.0237384 ]
  [0.04384353 0.17962104 0.14588311]]]

**Задание 4.**
Создать матрицу с 0 внутри, и 1 на границах.

In [92]:
matrix = np.ones((5, 5), dtype=int)
matrix[1: -1, 1: -1] = 0
print(matrix)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]

**Задание 5.**
Создайте массив и отсортируйте его по убыванию.

In [129]:
arr = np.random.randint(0, 90, (10))
sorted_arr = np.sort(arr)[::-1]
print(sorted_arr)

[77 75 70 61 59 50 41 13  3  2]

**Задание 6.**
Создайте матрицу, выведите ее форму, размер и размерность.

In [151]:
matrix = np.random.randint(0, 50, (4, 4))
print(matrix, '\n')
print(f'Форма: {np.shape(matrix)}\n')
print(f'Размер: {np.size(matrix)}\n')
print(f'Размерность: {np.ndim(matrix)}')

[[10 48 29 17]
 [40 48 41 25]
 [ 9 17 15  5]
 [39  6 23 32]]

Форма: (4, 4)

Размер: 16

Размерность: 2

# Pandas

**Задание 1.**
Найдите евклидово расстояние между двумя Series (точками) a и b, не 
используя встроенную формулу.

In [8]:
import pandas as pd

In [12]:
a = pd.Series([1, 2, 3, 4, 5])
b = pd.Series([6, 7, 8, 9, 10])

dist = ((a - b)**2).sum()**0.5

print(dist)

11.180339887498949

**Задание 2.**
Найдите в Интернете ссылку на любой csv файл и сформируйте из него 
фрейм данных (например, коллекцию фреймов данных можно найти 
здесь: https://github.com/akmand/datasets).

In [15]:
df = pd.read_csv("baby_names_2000.csv")
df.head(5)

   year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

**Задание 3.**
Проделайте с получившемся из предыдущего задания фреймом данных те же действия, что и в примерах 2.2.5-2.2.7.

Пронализировать характеристики фрейма данных.

In [20]:
print(f'Первые пять элементов:')
df.head(5)

Первые пять элементов:

   year     name gender  count
0  2000    Emily      F  25956
1  2000   Hannah      F  23082
2  2000  Madison      F  19968
3  2000   Ashley      F  17997
4  2000    Sarah      F  17702

In [22]:
print(f'Последние три элемента:')
df.tail(3)

Последние три элемента:

        year   name gender  count
624233  2018  Zyrie      M      5
624234  2018  Zyron      M      5
624235  2018  Zzyzx      M      5

In [24]:
print(f'Форма:')
df.shape

Форма:

(624236, 4)

In [26]:
print(f'Описательная статистика числовых столбцов:')
df.describe()

Описательная статистика числовых столбцов:

                year          count
count  624236.000000  624236.000000
mean     2009.115961     113.971929
std         5.383550     754.696900
min      2000.000000       5.000000
25%      2005.000000       7.000000
50%      2009.000000      11.000000
75%      2014.000000      29.000000
max      2018.000000   34477.000000

Выберите индивидуальные данные или срезы фрейма данных.

In [30]:
df.iloc[1:10]

   year       name gender  count
1  2000     Hannah      F  23082
2  2000    Madison      F  19968
3  2000     Ashley      F  17997
4  2000      Sarah      F  17702
5  2000     Alexis      F  17629
6  2000   Samantha      F  17265
7  2000    Jessica      F  15709
8  2000  Elizabeth      F  15099
9  2000     Taylor      F  15078

Требуется  отобрать  строки  фрейма  данных  на  основе некоторого 
условия. Необходимо сформировать новый фрейм данных из девочек.

In [33]:
df[df['gender'] == 'F'].head(10)

   year       name gender  count
0  2000      Emily      F  25956
1  2000     Hannah      F  23082
2  2000    Madison      F  19968
3  2000     Ashley      F  17997
4  2000      Sarah      F  17702
5  2000     Alexis      F  17629
6  2000   Samantha      F  17265
7  2000    Jessica      F  15709
8  2000  Elizabeth      F  15099
9  2000     Taylor      F  15078

#  Работа с числовыми данными

Загрузить фрейм данных по ссылке: 
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv. 
Необходимо выполнить нормализацию первого числового признака 
(sepal_length_cm) с использованием минимаксного преобразования, а 
второго (sepal_width_cm) с задействованием z-масштабирования.

In [4]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [6]:
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

In [8]:
print("Первые 5 строк исходных данных:")
print(df.head())
print("\nОписательная статистика до нормализации:")
print(df[['sepal_length_cm', 'sepal_width_cm']].describe())

Первые 5 строк исходных данных:
   sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm species
0              5.1             3.5              1.4             0.2  setosa
1              4.9             3.0              1.4             0.2  setosa
2              4.7             3.2              1.3             0.2  setosa
3              4.6             3.1              1.5             0.2  setosa
4              5.0             3.6              1.4             0.2  setosa

Описательная статистика до нормализации:
       sepal_length_cm  sepal_width_cm
count       150.000000      150.000000
mean          5.843333        3.054000
std           0.828066        0.433594
min           4.300000        2.000000
25%           5.100000        2.800000
50%           5.800000        3.000000
75%           6.400000        3.300000
max           7.900000        4.400000

In [10]:
min_max_scaler = MinMaxScaler()
df['sepal_length_normalized_minmax'] = min_max_scaler.fit_transform(df[['sepal_length_cm']])

In [12]:
standard_scaler = StandardScaler()
df['sepal_width_standardized_z'] = standard_scaler.fit_transform(df[['sepal_width_cm']])

In [14]:
print("\nРезультаты после нормализации (первые 5 строк):")
print(df[['sepal_length_cm', 'sepal_length_normalized_minmax', 
          'sepal_width_cm', 'sepal_width_standardized_z']].head())

Результаты после нормализации (первые 5 строк):
   sepal_length_cm  sepal_length_normalized_minmax  sepal_width_cm  \
0              5.1                        0.222222             3.5
1              4.9                        0.166667             3.0
2              4.7                        0.111111             3.2
3              4.6                        0.083333             3.1
4              5.0                        0.194444             3.6

   sepal_width_standardized_z
0                    1.032057
1                   -0.124958
2                    0.337848
3                    0.106445
4                    1.263460